packages:
  - packages/*
  - examples/*

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  http-proxy-middleware@>=3.0.0 <3.0.4: '>=3.0.4'
  http-proxy-middleware@>=3.0.0 <3.0.5: '>=3.0.5'
  koa@<2.16.1: '>=2.16.1'
  koa@>=2.0.0 <2.15.4: '>=2.15.4'
  koa@>=2.0.0 <2.16.2: '>=2.16.2'
  tmp@<=0.2.3: '>=0.2.4'
